//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPhotosServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Attribute", Namespace="http://schemas.datacontract.org/2004/07/MyPhotos", IsReference=true)]
    public partial class Attribute : object
    {
        
        private MyPhotosServiceReference.DataFile DataFileField;
        
        private int DataFileIdField;
        
        private int IdField;
        
        private string NameField;
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MyPhotosServiceReference.DataFile DataFile
        {
            get
            {
                return this.DataFileField;
            }
            set
            {
                this.DataFileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DataFileId
        {
            get
            {
                return this.DataFileIdField;
            }
            set
            {
                this.DataFileIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataFile", Namespace="http://schemas.datacontract.org/2004/07/MyPhotos", IsReference=true)]
    public partial class DataFile : object
    {
        
        private System.Collections.Generic.List<MyPhotosServiceReference.Attribute> AttributesField;
        
        private System.DateTime CreationDateField;
        
        private System.Nullable<bool> DeletedField;
        
        private int IdField;
        
        private string LocationField;
        
        private string NameField;
        
        private string PathField;
        
        private System.Collections.Generic.List<MyPhotosServiceReference.Tag> TagsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<MyPhotosServiceReference.Attribute> Attributes
        {
            get
            {
                return this.AttributesField;
            }
            set
            {
                this.AttributesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDate
        {
            get
            {
                return this.CreationDateField;
            }
            set
            {
                this.CreationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Deleted
        {
            get
            {
                return this.DeletedField;
            }
            set
            {
                this.DeletedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location
        {
            get
            {
                return this.LocationField;
            }
            set
            {
                this.LocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Path
        {
            get
            {
                return this.PathField;
            }
            set
            {
                this.PathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<MyPhotosServiceReference.Tag> Tags
        {
            get
            {
                return this.TagsField;
            }
            set
            {
                this.TagsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tag", Namespace="http://schemas.datacontract.org/2004/07/MyPhotos", IsReference=true)]
    public partial class Tag : object
    {
        
        private System.Collections.Generic.List<MyPhotosServiceReference.DataFile> DataFilesField;
        
        private int IdField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<MyPhotosServiceReference.DataFile> DataFiles
        {
            get
            {
                return this.DataFilesField;
            }
            set
            {
                this.DataFilesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyPhotosServiceReference.IMyPhotosFacade")]
    public interface IMyPhotosFacade
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceAttribute/AddAttribute", ReplyAction="http://tempuri.org/InterfaceAttribute/AddAttributeResponse")]
        System.Threading.Tasks.Task<bool> AddAttributeAsync(MyPhotosServiceReference.Attribute attribute);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceAttribute/UpdateAttribute", ReplyAction="http://tempuri.org/InterfaceAttribute/UpdateAttributeResponse")]
        System.Threading.Tasks.Task<MyPhotosServiceReference.Attribute> UpdateAttributeAsync(MyPhotosServiceReference.Attribute attribute);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceAttribute/DeleteAttribute", ReplyAction="http://tempuri.org/InterfaceAttribute/DeleteAttributeResponse")]
        System.Threading.Tasks.Task<int> DeleteAttributeAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceAttribute/GetAttributeById", ReplyAction="http://tempuri.org/InterfaceAttribute/GetAttributeByIdResponse")]
        System.Threading.Tasks.Task<MyPhotosServiceReference.Attribute> GetAttributeByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceAttribute/GetAttributes", ReplyAction="http://tempuri.org/InterfaceAttribute/GetAttributesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<MyPhotosServiceReference.Attribute>> GetAttributesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceDataFile/AddDataFile", ReplyAction="http://tempuri.org/InterfaceDataFile/AddDataFileResponse")]
        System.Threading.Tasks.Task<bool> AddDataFileAsync(MyPhotosServiceReference.DataFile file);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceDataFile/UpdateDataFile", ReplyAction="http://tempuri.org/InterfaceDataFile/UpdateDataFileResponse")]
        System.Threading.Tasks.Task<MyPhotosServiceReference.DataFile> UpdateDataFileAsync(MyPhotosServiceReference.DataFile file);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceDataFile/DeleteDataFile", ReplyAction="http://tempuri.org/InterfaceDataFile/DeleteDataFileResponse")]
        System.Threading.Tasks.Task<int> DeleteDataFileAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceDataFile/GetDataFileById", ReplyAction="http://tempuri.org/InterfaceDataFile/GetDataFileByIdResponse")]
        System.Threading.Tasks.Task<MyPhotosServiceReference.DataFile> GetDataFileByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceDataFile/GetDataFiles", ReplyAction="http://tempuri.org/InterfaceDataFile/GetDataFilesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<MyPhotosServiceReference.DataFile>> GetDataFilesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceTag/AddTag", ReplyAction="http://tempuri.org/InterfaceTag/AddTagResponse")]
        System.Threading.Tasks.Task<bool> AddTagAsync(MyPhotosServiceReference.Tag tag, MyPhotosServiceReference.DataFile file);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceTag/UpdateTag", ReplyAction="http://tempuri.org/InterfaceTag/UpdateTagResponse")]
        System.Threading.Tasks.Task<MyPhotosServiceReference.Tag> UpdateTagAsync(MyPhotosServiceReference.Tag tag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceTag/DeleteTag", ReplyAction="http://tempuri.org/InterfaceTag/DeleteTagResponse")]
        System.Threading.Tasks.Task<int> DeleteTagAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceTag/GetTagById", ReplyAction="http://tempuri.org/InterfaceTag/GetTagByIdResponse")]
        System.Threading.Tasks.Task<MyPhotosServiceReference.Tag> GetTagByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InterfaceTag/GetTags", ReplyAction="http://tempuri.org/InterfaceTag/GetTagsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<MyPhotosServiceReference.Tag>> GetTagsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IMyPhotosFacadeChannel : MyPhotosServiceReference.IMyPhotosFacade, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class MyPhotosFacadeClient : System.ServiceModel.ClientBase<MyPhotosServiceReference.IMyPhotosFacade>, MyPhotosServiceReference.IMyPhotosFacade
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MyPhotosFacadeClient() : 
                base(MyPhotosFacadeClient.GetDefaultBinding(), MyPhotosFacadeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_InterfaceMyPhotosFacade.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MyPhotosFacadeClient(EndpointConfiguration endpointConfiguration) : 
                base(MyPhotosFacadeClient.GetBindingForEndpoint(endpointConfiguration), MyPhotosFacadeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MyPhotosFacadeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MyPhotosFacadeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MyPhotosFacadeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MyPhotosFacadeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MyPhotosFacadeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<bool> AddAttributeAsync(MyPhotosServiceReference.Attribute attribute)
        {
            return base.Channel.AddAttributeAsync(attribute);
        }
        
        public System.Threading.Tasks.Task<MyPhotosServiceReference.Attribute> UpdateAttributeAsync(MyPhotosServiceReference.Attribute attribute)
        {
            return base.Channel.UpdateAttributeAsync(attribute);
        }
        
        public System.Threading.Tasks.Task<int> DeleteAttributeAsync(int id)
        {
            return base.Channel.DeleteAttributeAsync(id);
        }
        
        public System.Threading.Tasks.Task<MyPhotosServiceReference.Attribute> GetAttributeByIdAsync(int id)
        {
            return base.Channel.GetAttributeByIdAsync(id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<MyPhotosServiceReference.Attribute>> GetAttributesAsync()
        {
            return base.Channel.GetAttributesAsync();
        }
        
        public System.Threading.Tasks.Task<bool> AddDataFileAsync(MyPhotosServiceReference.DataFile file)
        {
            return base.Channel.AddDataFileAsync(file);
        }
        
        public System.Threading.Tasks.Task<MyPhotosServiceReference.DataFile> UpdateDataFileAsync(MyPhotosServiceReference.DataFile file)
        {
            return base.Channel.UpdateDataFileAsync(file);
        }
        
        public System.Threading.Tasks.Task<int> DeleteDataFileAsync(int id)
        {
            return base.Channel.DeleteDataFileAsync(id);
        }
        
        public System.Threading.Tasks.Task<MyPhotosServiceReference.DataFile> GetDataFileByIdAsync(int id)
        {
            return base.Channel.GetDataFileByIdAsync(id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<MyPhotosServiceReference.DataFile>> GetDataFilesAsync()
        {
            return base.Channel.GetDataFilesAsync();
        }
        
        public System.Threading.Tasks.Task<bool> AddTagAsync(MyPhotosServiceReference.Tag tag, MyPhotosServiceReference.DataFile file)
        {
            return base.Channel.AddTagAsync(tag, file);
        }
        
        public System.Threading.Tasks.Task<MyPhotosServiceReference.Tag> UpdateTagAsync(MyPhotosServiceReference.Tag tag)
        {
            return base.Channel.UpdateTagAsync(tag);
        }
        
        public System.Threading.Tasks.Task<int> DeleteTagAsync(int id)
        {
            return base.Channel.DeleteTagAsync(id);
        }
        
        public System.Threading.Tasks.Task<MyPhotosServiceReference.Tag> GetTagByIdAsync(int id)
        {
            return base.Channel.GetTagByIdAsync(id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<MyPhotosServiceReference.Tag>> GetTagsAsync()
        {
            return base.Channel.GetTagsAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_InterfaceMyPhotosFacade))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_InterfaceMyPhotosFacade))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8000/PC");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MyPhotosFacadeClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_InterfaceMyPhotosFacade);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MyPhotosFacadeClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_InterfaceMyPhotosFacade);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_InterfaceMyPhotosFacade,
        }
    }
}
